### ISSUE TITLE
article

### ISSUE THREAD

**Issue by PDmeaning** [teddybearxzh/UAV-Communication#1]
Is there any relevant article,please? thank you.

**Comment by teddybearxzh** [comment]
> Is there any relevant article,please? thank you.

Sure. These articles may help you.

1. **Air-to-ground modeling**: W. Feng, J. Wang, Y. Chen, X. Wang, N. Ge and J. Lu, "UAV-Aided MIMO Communications for 5G Internet of Things," in IEEE Internet of Things Journal, vol. 6, no. 2, pp. 1731-1740, April 2019, doi: 10.1109/JIOT.2018.2874531.
2. **User scheduling**: Y. Wang, W. Feng, Y. Li, S. Zhou and J. Wang, "Coordinated User Scheduling for Multi-Cell Distributed Antenna Systems," 2011 IEEE Global Telecommunications Conference - GLOBECOM 2011, Houston, TX, USA, 2011, pp. 1-5, doi: 10.1109/GLOCOM.2011.6133572.
3. **Power Allocation**: Y. Wang, W. Feng, Y. Zhao, S. Zhou and J. Wang, "Joint power allocation for multi-cell distributed antenna systems with large-scale CSIT," 2012 IEEE International Conference on Communications (ICC), Ottawa, ON, 2012, pp. 5264-5269, doi: 10.1109/ICC.2012.6364313.

I applied these two approaches to multiple-UAV-to-Multiple-users models. Hope this can answer your question.
